### PR TITLE
New website changes

### PR DESCRIPTION
**Pull request by Patowhiz**
@maxwellfundi this PR has changes to the following;

1. Newsletter Ribbon – Align the icon and test
2. Audio Pack – Make audio icons smaller
3. Newsletter page – Add thumbnail in English. You can change the desired thumbnail image, if need be.
4. Digital Parenting page – Add feature for show more to make text shorter
5. Impact counter - Add a counter to the numbers

### CODE REVIEW

**Comment by Patowhiz** [comment]
Will be pushing more changes to this PR.

**Comment by maxwellfundi** [comment]
Okay great, keep me posted, We need something to show fairly soon! cheers man.

**Comment by maxwellfundi** [comment]
@Patowhiz  And while you are at this can you correct the comics aspect ratio on mobile 

image

**Comment by maxwellfundi** [comment]
Let me know if you need any help.

**Comment by Patowhiz** [comment]
@maxwellfundi made changes to the following;

cosmic visuals on mobile fixed.
Newsletter page – Add thumbnail in English. You can change the desired thumbnail image, if need be.
Digital Parenting page – Add feature for show more to make text shorter

**Pull request merged**
