### PR TITLE
New website Fixes

### PR DESCRIPTION
**Pull request by Patowhiz**
@maxwellfundi this is now ready for review.

### CODE REVIEW

**Comment by maxwellfundi** [comment]
@Patowhiz there doesn't seem to be any changes on here

**Comment by Patowhiz** [comment]
@maxwellfundi . I have now synced my changes

**Comment by Patowhiz** [comment]
@maxwellfundi please note. I have centered the images. But that makes the left alignment of the headers to be distinct.

**Comment by Patowhiz** [comment]
@maxwellfundi  I've removed the roundness of the main column headers that define pages as requested.

**Comment by maxwellfundi** [comment]
Alright, Let me have a loook at this.

**Pull request merged**
